---
title: "Testing Business Logic"
author: "Troy Reynolds"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



## Gather Data
```{r get_data, echo=FALSE, eval = TRUE}
# Creat Function
get_tasks <- function() {
  vrtoolbox::sql.initialize_connector("data_science") %>%
    vrtoolbox::sql.run_query(
      .CON = .,
      .QUERY = "select * from scheduled_tasks"
    )
}

# Try to run function
get_tasks()
```


## Pie Plot testing
```{r plot, echo=FALSE}
library(ggplot2)

.AUTHOR <- "treynolds"
.COLUMN <- "HostName"
.DATA <- get_tasks()

pie_plot <- function(.DATA, .AUTHOR, .COLUMN) {
  
  
  DATA <- .DATA |> 
    # Only get desired authors
    dplyr::filter(Author %in% .AUTHOR) |>
    
    # Get breakdown of desired column
    dplyr::group_by(across(all_of(.COLUMN))) |> 
    dplyr::summarise(num = dplyr::n()) |> 
    
    # Mutate to get lables
    dplyr::mutate(
      csum = rev(cumsum(rev(num))), 
      pos = num/2 + dplyr::lead(csum, 1),
      pos = ifelse(is.na(pos), num/2, pos)
    )
  
  if(nrow(DATA) > 0 & !is.null(DATA)) {
    DATA |>
    # Plot the pie chart
    ggplot(aes(x = '', y = num, fill = get(.COLUMN))) + 
    geom_bar(stat="identity", width=1) + 
    scale_fill_discrete(name = .COLUMN) +
    coord_polar("y", start=0) +
    geom_text(aes(label = num), position = position_stack(vjust = 0.5), size = 6) + 
    guides(fill = guide_legend(title = "Group")) +
    scale_y_continuous(breaks = DATA$pos, labels = DATA[[.COLUMN]]) +
    theme(axis.ticks = element_blank(),
          axis.title = element_blank(),
          axis.text = element_text(size = 10, face = "bold"), 
          legend.position = "none", # Removes the legend
          panel.background = element_rect(fill = "white"))
  } else{return(NULL)}
}


pie_plot(get_tasks(), "treynolds", "HostName")
```


## Alternative Pie Plot testing
```{r alt plot, echo=FALSE}
library(ggplot2)

.AUTHOR <- "treynolds"
.COLUMN <- "HostName"
.DATA <- get_tasks()

pie_plot <- function(.DATA, .AUTHOR, .COLUMN) {
  
  
  DATA <- .DATA |> 
    # Only get desired authors
    dplyr::filter(Author %in% .AUTHOR) |>
    
    # Get breakdown of desired column
    dplyr::group_by(across(all_of(.COLUMN))) |> 
    dplyr::summarise(num = dplyr::n()) |> 
    
    # Mutate to get lables
    dplyr::mutate(
      csum = rev(cumsum(rev(num))), 
      pos = num/2 + dplyr::lead(csum, 1),
      pos = ifelse(is.na(pos), num/2, pos)
    )
    
  DATA |>
    # Plot the pie chart
    ggplot(aes(x = '', y = num, fill = get(.COLUMN))) + 
    geom_bar(stat="identity", width=1) + 
    scale_fill_discrete(name = .COLUMN) +
    coord_polar("y", start=0) +
    ggrepel::geom_label_repel(
      data = DATA,
      aes(y = pos, label = num),
      size = 4.5, nudge_x = 1, show.legend = FALSE
    ) + 
    guides(fill = guide_legend(title = "Group")) +
    theme_void()
}


pie_plot(get_tasks(), "treynolds", "Last Result")
```

## Number of Broken Tasks Function
```{r broken tasks}
.DATA <- get_tasks()

get_num_broken_tasks <- function(.DATA) {
  .DATA |>
    dplyr::filter(`Last Result` != "SUCCESS") |>
    nrow()
}


```


